# -*- coding: utf-8 -*-
"""Built-in function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-uNXCMw5kRLNPhBWbYFbfO0PKhXZEZdF
"""

#1. Write a program to find the length of a string entered by the user.
name = input("Enter name")
print(len(name))

#2. Write a program to take a number from the user and display its data type.
num=int(input("enter num"))
print(type(num))

#3. Write a program to take two numbers from the user and print their sum using type conversion.
a=int(input("enter num"))
b=int(input("enter num"))
sum=int(a)+int(b)
print(sum)

#4. Write a program to find the maximum of two numbers using a built-in function.
num1=int(input("enter num1"))
num2=int(input("enter num2"))
print(max(num1,num2))

#5. Write a program to take a string input and display it in uppercase.
str=input("enter the string")
print(str.upper())

#6. Write a program to display the first and last character of a string.
a=input("enter the string ")
print(a[0],a[-1])

#7. Write a program to check whether a string is empty or not.
str=input("enter the string")
if str=="":
  print("the string is empty")
else:
  print("string is not empty")

#8. Write a program to count the number of characters in a string without using len().
a= input("enter the string")
count=0
for i in a:
  count+=1
print(count)

#9. Write a program to reverse a string.
name="Nikita"
print(name[ : :-1])

#10. Write a program to check whether a given string is a palindrome.
name=input("enter the name")
if name==name[ : :-1]:
  print("the string is palindrom")
else:
  print("the string is not palindrome")

#11. Write a program to convert a string into lowercase and uppercase.
a=input("enter the string")
print(a.upper())
print(a.lower())

#12. Write a program to remove extra spaces from the beginning and end of a string.
a="                          ghhff               "
print(a.strip())

#13. Write a program to replace a word in a string with another word.
a="i love java"
print(a.replace("java","python"))

#14. Write a program to find the position of a word in a sentence.
a= "i love python"
print(a.find("python"))

#15 write a program to split the sentence into word.
a="i love coding"
print(a.split())

#16 write a program to take user name , remove spaces,and displaythe total no. of characters
a=input("enter the string")
new=a.strip()
print(new+len(new))

#17.write a program to check whether an email id contains @symbol
a=input("enter the email id ")
if "@" in a:
  print("valid emailid")
else:
  print("invalid email id")

#18. write the program to count the number of vowels in string
s = input("Enter a string ").lower()
count = 0
for ch in s:
    if ch in "aeiou":
        count += 1
print("Number of vowels:", count)

#19.write a program to take the sentence and count how many word it contains
a=input("enter the sentence")
new=a.split()
print(new,len(new))

#20.write the programe to take thestring from user and display each character one by one using loop
s = input("Enter a string ")
for ch in s:
    print(ch)

name = "Nikita"
print(name[-1])

name="python"
print(name.upper())

name="                    nikita              "
print(name.strip())

#split()
sentence= "python is easy"
print(sentence.split())

name=input("enter your name")
arg="@"
print(arg+name.lower()+str(len(name)))

