# -*- coding: utf-8 -*-
"""Copy of Day1python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tij7CYYYq0KeN54O3Hm6Bi5DsI7WzYC-
"""

age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible to vote")
else:
    print("You are not eligible to vote")

marks=int(input("entre your marks"))
if marks>=40:
  print("Pass")
else:
  Print("fail")

for i in range(1,6):
  marks=int(input("enter your marks"))
  if marks>=40:
    print ("pass")
  else:
    print("fail")
print("-------end----------")

num=int(input("enter num"))
if num % 2 == 0:
  print("even")
else:
  print("odd")

num= int(input("enter num"))
if num % 5 == 0 and num % 10 == 0:
  print("num is divisible by both")
else:
  print("num is not divisible by both")

a=input("enter character:")
if a in 'aeiou':
  print("vowel")
else:
  print("consonant")

year= int(input("enter year"))
if year % 4 == 0:
  print("leap year")
else:
  print("not a leap year")

units = float(input("Enter units consumed: "))
bill = units * 7


print(bill)

salary = int(input("enter your salary"))
if salary >=50000:
  bonus=salary+28000
else:
  bonus=salary+15000
print("bonus:",bonus )

for i in range(1,51):
  if i % 2 == 0:
    print(i)

total=sum(range(1,11))
print(total)

num=int(input("enter num:"))
for i in range(1,11):
  print(num*i)

num= input("enter num:")
print("lenght of given digit:",len(num))

for i in range(1,101):
  if i % 2 == 0:
    print(i,"Even")
  else:
    print(i,"odd")

for i in range(1,50):
  if i % 3 == 0:
    print(i)

total=0
for i in range(5):
  marks=int(input("enter marks"))
  total+=marks
average=total/5
print (average)

for i in range(5):
  num=int(input("enter num"))
  if num >0:
    print("positive")
  else:
    print("negative")

salary=int(input("enter your salary "))
if salary>50000:
  bonus=salary*0.1
else:
  bonus= salary*0.05
print(bonus)

for i in range (1,11):
  print(i)

num =input("enter num")
print(len(num))