# -*- coding: utf-8 -*-
"""lab Asignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3vEphT0JC6jFbkNe1rJcuSVt2Pi5CB7

1.Program to check leap year
"""

year= int(input("Enter year"))
if year % 4 == 0:
  Print("leap Year")
else:
  print("not a leap Year")

"""2. Python Program to Find the Largest Among Three Numbers"""

num1 = int(input("enter num1:"))
num2 = int (input("enter num2:"))
num3 = int (input ("enter num3:"))
if num1 >num2 and num1 > num3 :
  print(num1)
elif num2 > num1 and num2 > num3 :
  print(num2)
else:
  print(num3)

"""3. Python Program to Check if a Number is Positive, Negative or 0"""

num = int (input ("enter num:"))
if num>0:
  print("Positive")
elif num<0:
  print("negative")
else:
  print(0)

"""4. A toy vendor supplies three types of toys: Battery Based Toys, Key-based
Toys, and Electrical Charging Based Toys. The vendor gives a discount of
10% on orders for battery-based toys if the order is for more than Rs. 1000.
On orders of more than Rs. 100 for key-based toys, a discount of 5% is
given, and a discount of 10% is given on orders for electrical charging based
toys of value more than Rs. 500. Assume that the numeric codes 1,2 and 3
are used for battery based toys, key-based toys, and electrical charging based
toys respectively. Write a program that reads the product code and the order
amount and prints out the net amount that the customer is required to pay
after the discount.
"""

#product codes are :-Battery Based Toys =1 , Key-based Toys=2,Electrical Charging Based Toys=3
code = int(input("enter a product code :"))
amount= int(input("enter the amount:-"))
discount=0
if code == 1:
  if amount > 1000:
    discount=0.10*amount
elif code == 2:
  if amount >100:
    discount=0.05*amount
elif code == 3:
  if amount>500:
    discount=0.10*amount
print("you have to pay after applied discount:",amount-discount)

"""5.A transport company charges the fare according to following table: Distance Charges

1-50= 8 Rs./Km

51-100 =10 Rs./Km

>100= 12 Rs/Km
"""

distance=int(input("enter the distance"))
if distance >= 1 and distance <= 50:
  fare= distance*8
elif distance >= 51 and distance <=100:
  fare = distance*10
elif distance >=100:
  fare= distance*12
print (fare)

"""Assignment
1.write a python program to reverse a number using while loop
"""

num = int(input("Enter a number: "))
rev = 0

while num > 0:
    digit = num % 10
    rev = rev * 10 + digit
    num //= 10

print("Reversed number:", rev)

"""2.Write a python program to check whether the number is palindrom or not  """

num = int(input("Enter a number: "))
temp = num
rev = 0

while num > 0:
    rev = rev * 10 + num % 10
    num //= 10

if temp == rev:
    print("Palindrome number")
else:
    print("Not a palindrome")

"""3.Write a python program to find the factorial of given number using while loop"""

num = int(input("Enter a number: "))
fact = 1
while num > 0:
    fact *= num
    num -= 1

print(fact)

"""4.Accept numbers using input() function until the user enters 0. If user
input 0 then break the while loop and display the sum of all the
numbers.


"""

total = 0

while True:
    num = int(input("Enter a number (0 to stop): "))
    if num == 0:
        break
    total += num

print("Sum of numbers:", total)

"""Assignment:For loop
1.print first 10 natural number using fo loop
"""

for i in range(1,11):
  print(i)

"""2.Python program to chech string is palindrome or not

"""

str= input("enter string:")
if str==str[ : :-1]:
  print("string is palindrome")
else:
  print("string is not palindrome")

"""3.Python program to check if given number is armstrong number"""

num = int(input("Enter a number: "))
temp = num
digits = len(str(num))
sum_val = 0

while temp > 0:
    digit = temp % 10
    sum_val += digit ** digits
    temp //= 10

if sum_val == num:
    print("Armstrong number")
else:
    print("Not an Armstrong number")

"""4. Python program to get the Fibonacci series between 0 to 50"""

a, b = 0, 1

while a <= 50:
    print(a)
    a, b = b, a + b

"""5. Python program to check the validity of password input by users"""

password = input("Enter password: ")

if (len(password) >= 8 and
    any(c.isupper() for c in password) and
    any(c.islower() for c in password) and
    any(c.isdigit() for c in password)):
    print("Valid password")
else:
    print("Invalid password")