# -*- coding: utf-8 -*-
"""tuple dictionary list .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H2_AdTQE-VQcopGZFIfdHagMFw7OI0nb
"""

#1. Write a program to store 5 student marks in a list and display them.
marks=[]
for i in range(5):
  mark= int(input("enter your marks"))
  marks.append(mark)
print(marks)

#2. Write a program to find the largest number in a list.
a=[]
for i in range(5):
  num=int(input("enter the num"))
  a.append(num)
print(a,max(a))

#3. Write a program to count how many times a particular element appears in a list.
a= [22,33,22,45,95,33]
print(a.count(22))

#4. Write a program to add a new element to a list and remove an existing element.
a=[12,23,45,56]
a.append(36)
a.remove(23)
print(a)

#5. Write a program to calculate the sum of all elements in a list.
a=[1,2,4,6,7]
print(sum(a))

#6. Write a program to create a tuple of 5 numbers and display the second element.
a=[]
for i in range(5):
  num=int(input("enter num"))
  a.append(num)
print(a[1])

#7. Write a program to check whether an element exists in a tuple.
a=[2,4,5,7,8,9]
print(9 in (a))

#list
#*list is the collection of orderd and mutable elements that allow duplicate values eg. marks of students stored in list
marks = [20,30,45,60]
print(marks)

#8. Write a program to convert a tuple into a list.
a=(1,3,4,6,7)
lst=list(a)
print(lst)

#9. Write a program to find the length of a tuple.
a=(1,2,3,5,7)
print(len(a))

#10. Write a program to explain why tuple is immutable with an example.
a= (1,2,3,4,5,6,7)
a[3]=4
print(a)
print("tuples are immutable in nature")

#11. Write a program to store student details using a dictionary and display them.
student = {
    "name":"Nikita",
    "age":21,
    "course":"python"
}
print(student)

#12. Write a program to add a new key-value pair in a dictionary.
student = {
    "name": "Nikita",
    "marks": 85
    }
student["age"] = 20
print(student)

#13. Write a program to update the value of an existing key in a dictionary.
student={
    "name":"Nikita",
    "age":20
    }
student["name"]="Nisha"
print(student)

#14. Write a program to check whether a key exists in a dictionary.
student={
    "name":"Nikita",
    "age":20
    }
print( "name" in (student))

#15. Write a program to print all keys and values of a dictionary.
student_info={
    "Name":"Nikita",
    "age":20,
    "course":"python"
}
print(student_info.keys())
print(student_info.values())

#16. Write a program to create a set with duplicate values and display the output.
a={1,1,2,2,3,3,4,4,5,5,6,6}
print(a)

#17. Write a program to add a new element to a set.
a={1,2,4,5,6,7,8}
a.add(20)
print(a)

#18. Write a program to remove an element from a set.
a={1,2,3,4,5,6,7,9}
a.remove(3)
print(a)

#19. Write a program to find the union of two sets.
a={2,4,6,7,7,56,54,3,5}
b={5,3,5,6,4,6,3,4}
print(a.union(b))

#20. Write a program to find the intersection of two sets.
a={2,4,6,7,7,56,54,3,5}
b={5,3,5,6,4,6,3,4}
print(a.intersection(b))

marks[1]= 66
print(marks)

#tuple
#A tuple is  a collection of ordered  and immutable elements that allow duplicate
days=("mon","tue","wed")
print(days)

print(days[0])

days[1]="fri"
print(days)

#Dictionary
# A dictionary i sthe collection of key-value pair where each key is unique and used to acces it corresponding value
student = {
    "name":"Nikita",
    "age":21,
    "course":"python"
}
print(student["name"])

print(student["name"])

student["age"]=20
student["city"]="pune"
print(student)

#SET
# a set is an unorderd elements that does no tallow duplicates value
num={1,2,3,4,5,6,7,8}
print(num)

num.add(10)
print(num)

student_name= "nikita"
mark_list= [70,80,67]
unique_sub={"english","Hindi","Marathi"}

student_info={
    "name":student_name,
    "Marks":mark_list,
    "subject":unique_sub
}
print(student_info)